spring.application.name=demo

spring.datasource.url=jdbc:mysql://database-1.cra8uigk4i74.eu-north-1.rds.amazonaws.com:3306/mySqlTest
spring.datasource.username=admin
spring.datasource.password=Debe1234
spring.jpa.hibernate.ddl-auto=update
#//spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

